name: Manual Gate Control
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'open'
        type: choice
        options:
          - open
          - close
      count_of_runners_to_change_label:
        description: 'Optional: Number of runners to change (leave empty for all)'
        required: false
        type: string

jobs:
  manage_gate:
    runs-on: ubuntu-latest
    name: Manual Gate Control
    steps:
    - name: Set Gate State
      shell: bash
      run: |
        echo "Performing manual gate ${{ github.event.inputs.action }} operation"
        
        # Set limit count if provided
        LIMIT_COUNT="${{ github.event.inputs.count_of_runners_to_change_label }}"
        if [[ -n "$LIMIT_COUNT" && "$LIMIT_COUNT" =~ ^[0-9]+$ ]]; then
          echo "Will change labels for up to $LIMIT_COUNT runners"
          LIMIT_OPTION=true
        else
          echo "Will change labels for all applicable runners"
          LIMIT_OPTION=false
        fi
        
        if [[ "${{ github.event.inputs.action }}" == "close" ]]; then
          echo "Closing gate for postcommits - removing postcommit labels"
          query='.runners[] | select(.labels[].name=="ghrun") | select( any([.labels[].name][]; .=="postcommit")) | .id'
        else
          echo "Opening gate for postcommits - adding postcommit labels"
          query='.runners[] | select(.labels[].name=="ghrun") | select( all([.labels[].name][]; .!="postcommit")) | .id'
        fi
        
        echo "Requesting a list of runners to update labels..."
        j1=$(curl -Ls -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" -w "%{http_code}\n" \
          https://api.github.com/repos/${{github.repository}}/actions/runners?per_page=100\&page=1)
        http_code=$(echo "$j1" | tail -n 1)
        echo "Result code: $http_code"
        if [ "$http_code" != "200" ];then
          echo "HTTP result code is not 200, exiting"
          echo "$j1"
          exit 1
        fi
        
        # Extract runner IDs
        runner_ids=$(echo "$j1" | sed '$d' | jq "$query")
        
        # Count total eligible runners
        total_runners=$(echo "$runner_ids" | grep -v "^$" | wc -l)
        echo "Total eligible runners found: $total_runners"
        
        # Limit if needed
        if [[ "$LIMIT_OPTION" == "true" ]]; then
          runner_ids=$(echo "$runner_ids" | head -n $LIMIT_COUNT)
          echo "Limited to first $LIMIT_COUNT runners"
        fi
        
        # Process runners
        changed_count=0
        echo "$runner_ids" | while read x; do
          if [[ -z "$x" ]]; then continue; fi
          
          echo "Processing runner: $x"
          changed_count=$((changed_count + 1))
          
          if [[ "${{ github.event.inputs.action }}" == "close" ]]; then
            echo "Removing postcommit label from runner $x"
            result=$(curl -Ls -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{github.repository}}/actions/runners/$x/labels/postcommit)
          else
            echo "Adding postcommit label to runner $x"
            result=$(curl -Ls -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{github.repository}}/actions/runners/$x/labels \
              -d '{"labels":["postcommit"]}')
          fi
          echo "Result: $result"
        done
        
        echo "Gate ${{ github.event.inputs.action }} operation completed"
        echo "Summary: changed labels for runners out of $total_runners eligible runners"
